export const data = [
    {
        "Id":"0",
        "URL": "https://www.zomato.com/ncr/plum-by-bent-chair-aerocity-new-delhi",
        "Resturant_Name": "Plum By Bent Chair",
        "Address": "The Walk, Worldmark 2, Aerocity, New Delhi",
        "location": "Aerocity",
        "City": "New Delhi",
        "star_rating": "4.6",
        "Cuisines": "Asian",
        "Phone_Number": "011 61495178",
        "offer": "",
        "Cost_for_two": "₹1800",
        "Restaurant_Type": "",
     },
     {
         "Id":"1",
         "URL": "https://www.zomato.com/ncr/air-an-ivory-region-punjabi-bagh-new-delhi",
         "Resturant_Name": "AIR- An Ivory Region",
         "Address": "1/83, Third Floor, Club Road, West Punjabi Bagh, Punjabi Bagh, New Delhi",
         "location": "Punjabi Bagh",
         "City": "New Delhi",
         "star_rating": "4.0",
         "Cuisines": "North Indian",
         "Phone_Number": "011 66103930",
         "offer": "",
         "Cost_for_two": "₹1000",
         "Restaurant_Type": "",
      },
      {
          "Id":"2",
          "URL": "https://www.zomato.com/ncr/pa-pa-ya-saket-new-delhi",
          "Resturant_Name": "Pa Pa Ya",
          "Address": "Dome, Level 4, Select Citywalk, A-3, District Centre, Saket, New Delhi",
          "location": "Saket",
          "City": "New Delhi",
          "star_rating": "4.5",
          "Cuisines": "Asian",
          "Phone_Number": "011 66103779",
          "offer": "",
          "Cost_for_two": "₹2000",
          "Restaurant_Type": "",
       },
       {
           "Id":"3",
           "URL": "https://www.zomato.com/ncr/haldirams-sector-63-noida",
           "Resturant_Name": "Haldiram's",
           "Address": "1A/24, H-Block, Sector 63, Noida",
           "location": "Sector 63",
           "City": "Noida",
           "star_rating": "3.9",
           "Cuisines": "North Indian",
           "Phone_Number": "+91 8588000502",
           "offer": "",
           "Cost_for_two": "₹600",
           "Restaurant_Type": "Vegetarian",
        },
        {
            "Id":"4",
            "URL": "https://www.zomato.com/ncr/om-sweets-snacks-sector-31-gurgaon",
            "Resturant_Name": "Om Sweets & Snacks",
            "Address": "SCO 17, Main Market, Sector 31, Gurgaon",
            "location": "Sector 31",
            "City": "Gurgaon",
            "star_rating": "4.1",
            "Cuisines": "North Indian",
            "Phone_Number": "0124 4271101| 0124 4271102",
            "offer": "BOGO",
            "Cost_for_two": "₹500",
            "Restaurant_Type": "Vegetarian",
         },
         {
             "Id":"5",
             "URL": "https://www.zomato.com/ncr/cake-golf-course-road-gurgaon",
             "Resturant_Name": "Cake",
             "Address": "21, Golf Course Road, Gurgaon",
             "location": "Golf Course Road",
             "City": "Gurgaon",
             "star_rating": "2.8",
             "Cuisines": "Bakery",
             "Phone_Number": "+91 8860838157",
             "offer": "30% off on all dine-in and home-delivery orders. Offer on home-delivery only applicable when you order online on Zomato or the restaurant app.",
             "Cost_for_two": "₹300",
             "Restaurant_Type": "",
          },
   ]
               
   